### ISSUE TITLE
Memory crash when completing an action

### ISSUE THREAD

**Issue by ddobrev** [BranchMetrics/xamarin-branch-deep-linking#50]
Package: com.psonar.android
Version Code: 19840
Version Name: 4.18.0
Android: 5.1.1
Android Build: LMY47V.J111FXXU0APE4
Manufacturer: samsung
Model: SM-J111F
Thread: main-1
CrashReporter Key: 1596C7C1-775E-9710-8C5E-F37AB02D29F194B0619E
Start Date: Sun Mar 19 07:10:45 GMT+08:00 2017
Date: Sun Mar 19 19:35:36 GMT+08:00 2017
Format: Xamarin

Xamarin caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at io.branch.referral.ServerRequestQueue.persist(ServerRequestQueue.java:93)
	at io.branch.referral.ServerRequestQueue.enqueue(ServerRequestQueue.java:142)
	at io.branch.referral.Branch.handleNewRequest(Branch.java:2323)
	at io.branch.referral.Branch.userCompletedAction(Branch.java:1777)
	at io.branch.referral.Branch.userCompletedAction(Branch.java:1733)
	at io.branch.indexing.BranchUniversalObject.userCompletedAction(BranchUniversalObject.java:310)
	at io.branch.indexing.BranchUniversalObject.userCompletedAction(BranchUniversalObject.java:286)
	at com.psonar.android.GenreGroupActivity.n_onStart(Native Method)
	at com.psonar.android.GenreGroupActivity.onStart(GenreGroupActivity.java:42)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1264)
	at android.app.Activity.performStart(Activity.java:6647)
	at android.app.Activity.performRestart(Activity.java:6717)
	at android.app.ActivityThread.handleSleeping(ActivityThread.java:4694)
	at android.app.ActivityThread.access$3500(ActivityThread.java:218)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1964)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6934)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by antonargunov** [comment]
Hi @ddobrev , do you use last version of SDK?

**Comment by ddobrev** [comment]
I do.

**Comment by antonargunov** [comment]
@ddobrev , try new version of Xamarin SDK.
I checked method UserCompletedAction in our testbed.
All works.
